package:
  name: mageck
  version: "0.5.2"
source:
  path: ../../
requirements:
  build:
    - python
  run:
    - python
about:
  home: http://mageck.sourceforge.net
  license: BSD License
  summary: Model-based Analysis of Genome-wide CRISPR-Cas9 Knockout.
